name: Aya
favicon: null
layout_spectrum: 0.62287
typography_spectrum: 0.6748584234155715
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00dfaa'
    - '#7f9f55'
    - '#aa0000'
    - '#ff7f55'
  brandStrength: 0
  lightness: 0
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
