name: Aya
favicon: null
layout_spectrum: 0
typography_spectrum: 0.22768
title: Ayahuasca Journal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e2040'
    - '#f9eb57'
    - '#ef6a68'
    - '#0e90d3'
    - '#ae97d7'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
