name: AyaMountain
favicon: null
layout_spectrum: 0.15155
typography_spectrum: 0.22768
title: Ayahuasca Journal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f1a17'
    - '#595854'
    - '#e1e1df'
    - '#93928e'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
