name: Aya
favicon: null
layout_spectrum: 0.34784
typography_spectrum: 0.22768
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00a6ff'
    - '#006ff4'
    - '#1a51e9'
    - '#072a88'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
